FROM ubuntu:22.04
EXPOSE 9944
WORKDIR /var/www/node-template
RUN apt update && \
    apt install build-essential -y && \
    apt install curl git clang libssl-dev -y && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustsetup.sh && chmod -R 777 rustsetup.sh && ./rustsetup.sh -y && \
    PATH=$PATH:~/.cargo/bin/ && \
    rustup default stable && \
    rustup update && \
    rustup update nightly && \
    rustup target add wasm32-unknown-unknown --toolchain nightly && \
    rustup component add rust-src --toolchain nightly
    
ENV CARGO_HOME=/var/www/node-template/.cargo
COPY binaries /var/www/node-template
CMD ["bash"]
